# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHDV7ejsB2ri2WT-jth1RTXRIEPscdkS
"""

import random
l = []
for i in range(5):
  l.append(random.randrange(3,20,2))
print(l)

L = []
for x in range(4):
  L.append(random.randrange(0,20,2))
print(L)