# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_8QUKfEyqITSrwftxJfVzYS2BdMEUVY
"""

import random
num = [random.randint(1, 10) for_in range(20)]
print(nums)

n = int(input('enter a no: '))
positions = [i for i, val in enumerate(num) if val == n]
print('positions:', position if position else 'not found')